### ISSUE TITLE
Rare, but persistent NPEs during test execution in conjunction with forks

### ISSUE THREAD

**Issue by S1artie** [integrity-tf/integrity#122]
In a production project, the automated build sometimes fails due to no apparent reason with the following exception: 

```
    FORK 'abc': Process terminated!
    FORK 'abc': Process terminated!
java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:209)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.net.SocketInputStream.read(SocketInputStream.java:223)
    at de.gebit.integrity.remoting.transport.Endpoint$EndpointInputProcessor.run(Endpoint.java:241)
ERROR occurred during test runner execution!
java.lang.NullPointerException
    at de.gebit.integrity.runner.callbacks.xml.XmlWriterTestCallback.internalOnTearDownStart(XmlWriterTestCallback.java:1432)
    at de.gebit.integrity.runner.callbacks.xml.XmlWriterTestCallback.onTearDownStart(XmlWriterTestCallback.java:1421)
    at de.gebit.integrity.runner.callbacks.CompoundTestRunnerCallback.onTearDownStart(CompoundTestRunnerCallback.java:182)
    at de.gebit.integrity.runner.callbacks.CompoundTestRunnerCallback.onTearDownStart(CompoundTestRunnerCallback.java:182)
    at de.gebit.integrity.runner.DefaultTestRunner.executeTearDownSuites(DefaultTestRunner.java:977)
    at de.gebit.integrity.runner.DefaultTestRunner.callSuiteSingle(DefaultTestRunner.java:838)
    at de.gebit.integrity.runner.DefaultTestRunner.callSuite(DefaultTestRunner.java:682)
    at de.gebit.integrity.runner.DefaultTestRunner.executeSuite(DefaultTestRunner.java:1028)
    at de.gebit.integrity.runner.DefaultTestRunner.callSuiteSingle(DefaultTestRunner.java:809)
    at de.gebit.integrity.runner.DefaultTestRunner.callSuite(DefaultTestRunner.java:682)
    at de.gebit.integrity.runner.DefaultTestRunner.executeSuite(DefaultTestRunner.java:1028)
    at de.gebit.integrity.runner.DefaultTestRunner.callSuiteSingle(DefaultTestRunner.java:809)
    at de.gebit.integrity.runner.DefaultTestRunner.runInternal(DefaultTestRunner.java:635)
    at de.gebit.integrity.runner.DefaultTestRunner.run(DefaultTestRunner.java:513)
    at de.gebit.integrity.runner.DefaultTestRunner.run(DefaultTestRunner.java:448)
```

This looks like some race condition case...

**Comment by S1artie** [comment]
Version 0.15.8-SNAPSHOT has been tested by the project that found the original bug, and the problem did not occur anymore. I consider this to be fixed.

**Comment by S1artie** [comment]
Unfortunately the bug has reappeared, this issue is thus reopened.

**Comment by S1artie** [comment]
Closed, as this strange thing has not been observed to happen for quite a while now.
